close all;
clc;
clear;

image = imread('test_1.png');
im1 = imread('im_1.png');
im2 = imread('im_2.png');
struct = zeros(3,3);
f1 = figure(1);
    subplot(2, 2, 1);
        imshow(image);
        title('original image', fontsize = 16);
    subplot(2, 2, 2);
        imshow(struct);
        title('structuring element 3\times3', fontsize = 16);
    subplot(2, 2, 3);
        image3 = my_dilation(image);
        imshow(image3);
        title('dilation', fontsize = 16);
    subplot(2, 2, 4);
        image4 = my_erosion(image);
        imshow(image4);
        title('erosion', fontsize = 16);
f2 = figure(2);
    subplot(3, 2, 1);
        imshow(im1);
        title('original iamge1', fontsize = 16);
    subplot(3, 2, 2);
        imshow(im2);
        title('original iamge2', fontsize = 16);
    subplot(3, 2, 3);
        im_inter = set_cal(im1, im2, 0);
        imshow(im_inter);
        title('set intersection', fontsize = 16);
    subplot(3, 2, 4);
        im_diff = set_cal(im1, im2, 1);
        imshow(im_diff);
        title('set differencing', fontsize = 16);
    subplot(3, 2, 5);
        im_1_c = set_cal(im1, im2, 2);
        imshow(im_1_c);
        title('set complementation', fontsize = 16);
    subplot(3, 2, 6);
        im_2_c = set_cal(im1, im2, 3);
        imshow(im_2_c);
        title('set complementation', fontsize = 16);
